apiVersion: v1
kind: Pod
metadata:
  name: describe-demo
  labels:
    app: describe-demo
    tier: backend
    env: development
spec:
  containers:
    - name: nginx
      image: nginx:1.27
      ports:
        - containerPort: 80
          name: http
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
      env:
        - name: APP_ENV
          value: "development"
        - name: DEBUG_MODE
          value: "true"
