apiVersion: v1
kind: Pod
metadata:
  name: imagepull-demo
  labels:
    app: imagepull-demo
spec:
  containers:
    - name: web-server
      image: nginx:non-existent-v99.99
      ports:
        - containerPort: 80
