apiVersion: v1
kind: ConfigMap
metadata:
  name: app-settings
data:
  app.conf: |
    server_mode=production
    cache_enabled=true
---
apiVersion: v1
kind: Pod
metadata:
  name: containercreating-demo
  labels:
    app: containercreating-demo
spec:
  containers:
    - name: web-app
      image: nginx:1.27
      volumeMounts:
        - name: app-volume-mount
          mountPath: /etc/configs
  volumes:
    - name: app-volume-mount
      configMap:
        name: app-settings
