apiVersion: v1
kind: Pod
metadata:
  name: pending-demo
  labels:
    app: pending-demo
spec:
  nodeSelector:
    disktype: ultra-nvme-ssd-zone-b
  containers:
    - name: data-processor
      image: nginx:1.27
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
